Vagrant.configure("2") do |config|

# Uncomment this depending on the provider you want to us 
# ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'
defaults = ["shrek.lab", "192.168.56.10", "Ethernet 2"]
boxes = [
  # windows server 2022 : don't work for now
  #{ :name => "DC01",  :ip => "192.168.56.10", :box => "StefanScherer/windows_2022", :box_version => "2021.08.23", :os => "windows"},
  # windows server 2019
  { :name => "TestDC01",  :ip => "192.168.56.10", :box => "gusztavvargadr/windows-server", :os => "windows", :dc => true},
  { :name => "TestSRV02", :ip => "192.168.56.22", :box => "gusztavvargadr/windows-server", :os => "windows"},
  #{ :name => "ansiblehost", :ip => "192.168.56.30", :box => "ubuntu/jammy64", :os => "linux"}
  # ELK
# { :name => "elk", :ip => "192.168.56.50", :box => "bento/ubuntu-18.04", :os => "linux",
#   :forwarded_port => [
#     {:guest => 22, :host => 2210, :id => "ssh"}
#   ]
# }
]


  config.vm.provider "virtualbox" do |v|
    v.memory = 3800
    v.cpus = 2
  end


  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  boxes.each do |box|
    config.vm.define box[:name] do |target|
      # BOX
      target.vm.provider "virtualbox" do |v|
        v.name = box[:name]
      end
      target.vm.box_check_update = false
      target.vm.box = box[:box]

      # issues/49
      target.vm.synced_folder '.', '/vagrant', disabled: true

      # IP
      target.vm.network :private_network, ip: box[:ip]

      # OS specific
      if box[:os] == "windows"
        target.vm.guest = :windows
        target.vm.communicator = "winrm"
        target.winrm.transport = :plaintext
        target.winrm.basic_auth_only = true

      else
        target.vm.communicator = "ssh"
      end

      if box[:dc]
        target.vm.provision :shell, :path => "create-domain.ps1", :args => defaults, privileged: false
        target.vm.provision "reload"
      else
        target.vm.provision :shell, :path => "join-domain.ps1", :args => defaults, privileged: false
        target.vm.provision "reload"
      end
    end
  end
end
