---
# grub-pc loves to break cause it requires config
- name: hold grub upgrade
  dpkg_selections:
    name: grub-pc
    selection: hold

# we aren't dist-upgrading because that's a pain
- name: Upgrade all apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "*"
    state: latest
  ignore_errors: true