Vagrant.configure("2") do |config|
  config.vm.define "win10dev" do |cfg|
    cfg.vm.box = "gusztavvargadr/visual-studio"
    cfg.vm.box_version = "2022.2102.2205" # version pin this for testing
    cfg.vm.boot_timeout = 600
    cfg.vm.synced_folder '.', '/vagrant', disabled: false

    #cfg.vm.provision "shell", path: "generic_setup.ps1", privileged: false
    #cfg.vm.provision "shell", path: "logging.ps1", privileged: false
    #cfg.vm.provision "shell", path: "set-wallpaper.ps1", privileged: false,args: "dev"
    #cfg.vm.provision "shell", path: "boxstarter.ps1", privileged: false 
    cfg.vm.provision "shell", path: "setup_dev.ps1", privileged: false 

    cfg.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 6096]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
  end
end
  