- include_vars: vars/github_tools.yml
- include: install_4n6_tools.yml
#- include: install_xstreader.yml
#- include: install_hindsight.yml
#- include: install_chainsaw.yml
- include: load_github_tools.yml
- include: copy_image-mounting.yml
#- include: setup_autopsy_plugins.yml
#- include: setup_zimmerman.yml
#- include: setup_cheat-sheets.yml

# - include: download_example.yml
# xstreader
# diskmount utilities like ftk, arsenal
# sqlreader and browser history tools, hindsight
# registry explorer
# elex
# KAPE
# autopsy and plugins
# acquisition tools like cylr, kape, ... avml, 


# see here: https://awesomedfir.com/ and especially this list https://awesomedfir.com/dfir-tooling

# TODO: create module that does the install_xstreader 
#       and hindsight functionaility from a given github 
#       repo link to latest release
