# test images: https://digitalcorpora.org/corpora/disk-images 
# nps-2010-emails is pretty small
- name: download autopsy plugins
  win_get_url:
    url: '{{ item.value.url }}'
    dest: '{{ TEMP_PATH }}\{{ item.value.name }}.zip'
    force: no
  loop: '{{ autopsy_plugins | dict2items }}' # evaluate dict and return "list"
  ignore_errors: yes

- name: unzip autopsy plugins
  win_unzip:
    src: '{{ TEMP_PATH }}\{{ item.value.name }}.zip'
    dest: '{{ PLUGINS_PATH }}\{{ item.value.name }}'
    creates: '{{ PLUGINS_PATH }}\{{ item.value.name }}'
  loop: '{{ autopsy_plugins | dict2items }}' # evaluate dict and return "list"
  ignore_errors: yes

# https://superuser.com/questions/1333292/how-to-parse-a-directory-recursively-and-mklink-each-file-into-a-target-path-wit
# https://stackoverflow.com/questions/15248001/create-a-scheduled-task-that-runs-on-particular-user-login-using-commandline/41214760
#- name:
#  win_shell:
## schtasks /Create /TR executable.exe /RU user /TN name /SC ONLOGON /IT

- name: copy over autopsy-plugins-mklink.bat
  win_copy:
    src: '../files/{{ MKLINKBAT_FILE }}'
    dest: '{{ PLUGINS_PATH }}\{{ MKLINKBAT_FILE }}'
    force: no
  ignore_errors: yes

- name: Execute autopsy plugins mklink bat
  win_shell: '{{ PLUGINS_PATH }}\{{ MKLINKBAT_FILE }}'
  ignore_errors: yes