require 'yaml'
inventory = YAML.load_file('inventory.yml')
vars = inventory['all']['vars']
env = 
vmgroups = inventory['all']['children']

Vagrant.configure("2") do |config|
    vmgroups.each do |group,groupdetails| #TODO groups can be removed since no more ansible in use
        vmgroups[group]['hosts'].each do |host,details|
            config.vm.define host do |cfg|
                cfg.vm.box = details['vagrant_box']
                cfg.vm.box_check_update = false # we specifically set the version for most of them so it's stable
                cfg.vm.hostname = host
                # use the plaintext WinRM transport and force it to use basic authentication.
                # NB this is needed because the default negotiate transport stops working
                #    after the domain controller is installed.
                #    see https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
                if details.key?('winrm_plain') ? details['winrm_plain']: false then 
                    cfg.winrm.transport = :plaintext
                    cfg.winrm.basic_auth_only = true
                end
                # set host specific timeouts if available
                cfg.vm.boot_timeout = details.key?('boot_timeout') ? details['boot_timeout']: vars['default_host']['boot_timeout']
                cfg.winrm.timeout = details.key?('timeout') ? details['timeout']: vars['default_host']['timeout']
                #cfg.vm.network :private_network, ip: host_ip
                cfg.vm.synced_folder '.', '/vagrant', disabled: false
                # provison_args = "-ip " + details['ip'] + " -domain " + vars['domain_name'] + " -dns " + dns_server

                # execute host specific scripts if there are any
                if details.key?('scripts') then
                    details['scripts'].each do |script_name,script_data|
                        cfg.vm.provision "shell" do |shell|
                            shell.path = script_data['path']
                            shell.args = script_data['args']
                            # shell.env = {VAGRANT_DOMAIN:ENV['AWS_ACCESS_KEY'],AWS_ACCESS_KEY:ENV['AWS_ACCESS_KEY']} 
                            # shell.privileged = false
                        end
                        # reload if required after script
                        if script_data.key?('reload') ? script_data['reload'] : false then
                            cfg.vm.provision "reload"
                        end
                    end
                end

                cfg.vm.provider "virtualbox" do |vb, override|
                    vb.gui = true
                    vb.name = 'shreklab_' + host
                    # vb.default_nic_type = "82545EM"
                    vb.customize ["modifyvm", :id, "--memory", details.key?('memory') ? details['memory']: vars['default_host']['memory']]
                    vb.customize ["modifyvm", :id, "--cpus", details.key?('cpus') ? details['cpus']: vars['default_host']['cpus']]
                    vb.customize ["modifyvm", :id, "--vram", "32"]
                    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"] 
                    # check out '."C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" modifyvm' for options
                    # [--nic<1-N> none|null|nat|bridged|intnet|hostonly|generic|natnetwork]
                    # set all network interfaces either via host specific or default config
                    interfaces = details.key?('interfaces') ? details['interfaces']: vars['default_host']['interfaces']
                    interfaces.each do |adap_name,adap_data|
                        vb.customize ["modifyvm", :id, adap_data["type"][0], adap_data["type"][1]] # eg ["--nic2", "natnetwork"]
                        vb.customize ["modifyvm", :id, adap_data["name"][0], adap_data["name"][1]] # eg ["--nat-network2", "NatNetwork"]
                    end
                  # ... 
                end
            end
        end
    end
end