---
- name: increase priority of Interface
  win_shell: Set-NetIPInterface -InterfaceAlias "{{ default_host.iface }}" -InterfaceMetric 10 

- name: Change dns server to domain controller
  win_dns_client:
    adapter_names: "{{ default_host.iface }}"
    ipv4_addresses: "{{ default_host.dc_ip_dns }}"

- name: reboot | Rebooting after setting DNS server
  win_reboot:
  
- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900

- name: Join domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ users.admin1.name }}@{{ domain_name }}"
    domain_admin_password: "{{ users.admin1.pass }}"
    state: "domain"
  register: domain_state

- name: reboot | Reboot after joining domain
  win_reboot:
    msg: "Rebooting after joining domain"
  when: domain_state.reboot_required

- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900