- name: Disable firewall for Domain, Public and Private profiles
  win_firewall:
    state: disabled
    profiles:
    - Domain
    - Private
    - Public
  tags: disable_firewall
  when: ansible_facts['distribution_major_version'] != "6"

- name: Disable firewall for Win7
  win_shell: NetSh Advfirewall set allprofiles state off
  when: ansible_facts['distribution_major_version'] == "6"