# stole a bunch from https://github.com/ruzickap/ansible-role-my_common_defaults/blob/master/tasks/Win32NT-common.yml

# doesn't work
- name: Disable Logon Background Image
  win_regedit:
    path: 'HKLM:\Software\Policies\Microsoft\Windows\System'
    name: DisableLogonBackgroundImage
    data: 1
    type: dword

- name: Disable Hibernate Mode
  win_command: powercfg -h off
  changed_when: false
  when: ansible_distribution is search("Microsoft Windows 10")

- name: Create BGInfo structure
  win_file:
    path: C:\BGInfo
    state: directory

- name: Upload bginfo config file
  win_copy:
    src: ../files/devbox.bgi
    dest: 'C:\BGInfo\devbox.bgi'

- name: Upload bginfo wallpaper
  win_copy:
    src: ../files/i03fnmea06331.jpg
    dest: 'C:\BGInfo\i03fnmea06331.jpg'

- name: Start bginfo after login
  win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
    name: bginfo
    data: '%PROGRAMDATA%\chocolatey\bin\bginfo.exe C:\BGinfo\bginfo.bgi /silent /timer:0 /nolicprompt'

#- name: Enable Administrator account
#  win_user:
#    name: Administrator
#    account_disabled: no
#  when: ansible_distribution is search("Microsoft Windows 10")