# stole a bunch from https://github.com/ruzickap/ansible-role-my_common_defaults/blob/master/tasks/Win32NT-common.yml

# doesn't work
- name: Set Desktop Solid Color
  win_regedit:
    path: 'HKCU:\Control Panel\Colors'
    name: Background
    data: "74 84 89"

- name: Disable Logon Background Image
  win_regedit:
    path: 'HKLM:\Software\Policies\Microsoft\Windows\System'
    name: DisableLogonBackgroundImage
    data: 1
    type: dword

- name: Disable Hibernate Mode
  win_command: powercfg -h off
  changed_when: false
  when: ansible_distribution is search("Microsoft Windows 10")

- name: Upload bginfo config file
  win_copy:
    src: ../files/RedTeamLab.bgi
    dest: '%PROGRAMDATA%\bginfo.bgi'

- name: Start bginfo after login
  win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
    name: bginfo
    data: '%PROGRAMDATA%\chocolatey\bin\bginfo.exe %PROGRAMDATA%\bginfo.bgi /silent /timer:0 /nolicprompt'

#- name: Enable Administrator account
#  win_user:
#    name: Administrator
#    account_disabled: no
#  when: ansible_distribution is search("Microsoft Windows 10")