# iterating through lists https://stackoverflow.com/questions/64032017/iterating-through-two-lists-in-ansible
#- name: test iterate dict
#  debug:
#    msg: "{{ item }} \n {{ item | dict2items }} \n {{ item.value.name }}"
#  loop: '{{ users | dict2items }}'
#  ignore_errors: yes # if we rerun the playbook, this will fail the whole playbook, so don't worry about it if it fails


- name: set the vault protected admin users
  win_user:
    name: '{{ item.value.name }}' # this has key: <USERNAME> and value:<name:..., pass:...>
    password: '{{ item.value.pass }}'
    password_expired: no
    groups: Administrators, Remote Desktop Users
    state: present
  loop: '{{ users | dict2items }}' # evaluate dict and return "list"
  loop_control:
    label: 'create user: {{ item.value.name }}'
  #no_log: true # do not log passwords
  ignore_errors: yes # if we rerun the playbook, this will fail the whole playbook, so don't worry about it if it fails


#- name: set local admin password
#  win_user:
#    name: Administrator
#    password: "{{ win_password }}"
#    #password: "{{ local_admin_password }}"
#    password_expired: no
#    groups: Administrators, Remote Desktop Users
#    state: present
#  ignore_errors: yes # if we rerun the playbook, this will fail the whole playbook, so don't worry about it if it fails
#