Vagrant.configure("2") do |config|
# virtualbox VM name prefix 
prefix = "mallab" 
# DNS & gateway IP to point to and Interface that will be used as primary interface
defaults = ["10.10.10.1", "Ethernet 2"] 
# default VM ressource allocations
ressources = {:cpus => "2", :memory => "4096"}
boxes = [
  { 
    :name => "remnux",  
    :iface => [{:name => "mallab_internal",  :ip => "10.10.10.1"}], 
    :box => "mncmbb/remnuxv7_2004", 
    :os => "linux", 
    :scripts => [],
  },
  { 
  :name => "win11-test", 
  :iface => [{:name => "mallab_internal",  :ip => "10.10.10.22"}],
  :box => "gusztavvargadr/windows-11", 
  :os => "windows",
  :scripts => [{:path => "prepare-windows.ps1", :args => defaults, :reload => false}], 
  :memory => "8096",  
  },
# if you want to deploy elastic, see "minad" for a config 
#  { 
#  :name => "elastic", 
#  :iface => [{:name => "mallab_internal", :ip => "10.10.10.100"}], 
#  :box => "ubuntu/jammy64", 
#  :os => "linux",
#  :scripts => [{:path => "deploy-ecp.sh", :args => [], :reload => false}], 
#  :memory => "8096",
#  },
]

  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  boxes.each do |box|
    config.vm.define box[:name] do |target|
      # BOX
      target.vm.box_check_update = false 
      target.vm.hostname = box[:name]
      target.vm.provider "virtualbox" do |v|
        v.linked_clone = true
        v.name = prefix + "_" + box[:name]
        v.memory = box.key?(:memory) ? box[:memory] : ressources[:memory]
        v.cpus = box.key?(:cpus) ? box[:cpus] : ressources[:cpus]
        v.customize ["modifyvm", :id, "--vram", "32"]
        v.customize ["modifyvm", :id, "--groups", "/"+prefix]
        #v.customize ["modifyvm", :id, "--clipboard", "bidirectional"] 
        if box.key?(:natnet) 
          v.customize ["modifyvm", :id, "--nic4", "natnetwork"]             # set as nic4 to avoid collisions
          v.customize ["modifyvm", :id, "--nat-network4", "NatNetwork"]
        end
      end
      target.vm.box_check_update = false
      target.vm.box = box[:box]
      target.vm.synced_folder '.', '/vagrant', disabled: false

      # set IP 
      # for network config check https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/networking
      box[:iface].each do |iface|
        target.vm.network :private_network, ip: iface[:ip], virtualbox__intnet: iface[:name]
      end

      # OS specific
      if box[:os] == "windows"
        target.vm.guest = :windows
        target.vm.communicator = "winrm"
      else
        target.vm.communicator = "ssh"
      end

      # iterate through scripts if there are any
      if box.key?(:scripts)
        box[:scripts].each do |script|
          target.vm.provision :shell, :path => script[:path], :args => script[:args], privileged: false
          if script[:reload]
            target.vm.provision "reload"
          end
        end
      end

    end
  end
end
